SET TARGET_DATABASE = '&{ dbsname }';
SET DEPLOY_SCHEMA   = '&{ xmaname }';
SET POOL_NAME       = UPPER($DEPLOY_SCHEMA) || '_POOL';
SET STAPP_NAME      = UPPER($DEPLOY_SCHEMA) || '_STAPP';
SET STAPP_TITLE     = UPPER($DEPLOY_SCHEMA) || '-Admin';

USE ROLE ACCOUNTADMIN;
USE DATABASE IDENTIFIER($TARGET_DATABASE);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);

-- Upload rendered spec
REMOVE @SPECS PATTERN='.*yaml';
PUT file://.build/worker_spec.yaml @SPECS AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Upload app code
REMOVE @VOLUMES PATTERN='.*gz';
PUT file://.build/app.tar.gz @VOLUMES AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Upload Streamlit app
REMOVE @STREAMLITS PATTERN='.*py';
PUT file://streamlit/streamlit_app.py @STREAMLITS AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Resume compute pool
ALTER COMPUTE POOL IF EXISTS IDENTIFIER($POOL_NAME) RESUME IF SUSPENDED;

-- Recreate Streamlit app
CREATE OR REPLACE STREAMLIT IDENTIFIER($STAPP_NAME)
    ROOT_LOCATION = '@STREAMLITS'
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = 'COMPUTE_WH'
    TITLE = $STAPP_TITLE
    COMMENT = 'Queue processor monitoring and configuration dashboard';

-- Resume task
ALTER TASK RUNNER_TASK RESUME;
