SET TARGET_DATABASE = '&{ dbsname }';
SET DEPLOY_SCHEMA   = '&{ xmaname }';
SET POOL_NAME       = UPPER($DEPLOY_SCHEMA) || '_POOL';
SET STAPP_NAME      = UPPER($DEPLOY_SCHEMA) || '_STAPP';

USE ROLE ACCOUNTADMIN;
USE DATABASE IDENTIFIER($TARGET_DATABASE);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($DEPLOY_SCHEMA);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);

-- Suspend and drop task
ALTER TASK IF EXISTS RUNNER_TASK SUSPEND;
DROP TASK IF EXISTS RUNNER_TASK;

-- Drop Streamlit app
DROP STREAMLIT IF EXISTS IDENTIFIER($STAPP_NAME);

-- Drop stored procedures
DROP PROCEDURE IF EXISTS ORCHESTRATE_BATCH();
DROP PROCEDURE IF EXISTS ENQUEUE_REQUEST(VARCHAR, INT);
DROP PROCEDURE IF EXISTS QUEUE_STATUS();
DROP PROCEDURE IF EXISTS UPDATE_CONFIG(VARCHAR, VARCHAR);

-- Drop tables
DROP TABLE IF EXISTS PROCESS_LOG;
DROP TABLE IF EXISTS REQUEST_QUEUE;
DROP TABLE IF EXISTS RUNNER_CONFIG;

-- Suspend and drop compute pool
ALTER COMPUTE POOL IF EXISTS IDENTIFIER($POOL_NAME) SUSPEND;
DROP COMPUTE POOL IF EXISTS IDENTIFIER($POOL_NAME);

-- Drop stages
DROP STAGE IF EXISTS SPECS;
DROP STAGE IF EXISTS VOLUMES;
DROP STAGE IF EXISTS STREAMLITS;

-- Drop image repo
DROP IMAGE REPOSITORY IF EXISTS IMAGES;

-- Drop schema
DROP SCHEMA IF EXISTS IDENTIFIER($DEPLOY_SCHEMA);
